{% set name = "pyexpander" %}
{% set version = "2.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: e17b55324d5affbc82d8883779796de067137949840d64dabba53c3378f0d0fe

build:
  noarch: python
  number: 0
  script: '{{ PYTHON }} -m pip install . -vv '

requirements:
  host:
    - pip
    - setuptools
    - python >=3.5
  run:
    - python >={{ python_min }}

test:
  requires:
    - python {{ python_min }}
  imports:
    - pyexpander

about:
  home: https://goetzpf.bitbucket.io/pyexpander/index.html
  license: GPL-3.0-only
  license_family: GPL
  license_file: LICENSE.txt
  summary: a powerful macro processing language
  doc_url: https://goetzpf.bitbucket.io/pyexpander/index.html
  dev_url: https://bitbucket.org/goetzpf/pyexpander

extra:
  recipe-maintainers:
    - olawid
