{% set name = "pyexpander" %}
{% set version = "1.10.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 56aacb00e1daa7b04e6488a12d2f0ca5a8d75fc6360484efacfb02322d4ed55e

build:
  noarch: python
  number: 1
  script: '{{ PYTHON }} -m pip install . -vv '

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - python >={{ python_min }}

test:
  requires:
    - python {{ python_min }}
  imports:
    - pyexpander

about:
  home: https://goetzpf.bitbucket.io/pyexpander/index.html
  license: GPL-3.0
  license_family: GPL
  license_file: LICENSE.txt
  summary: a powerful macro processing language
  doc_url: https://goetzpf.bitbucket.io/pyexpander/index.html
  dev_url: https://bitbucket.org/goetzpf/pyexpander

extra:
  recipe-maintainers:
    - olawid
